### ISSUE TITLE
Unit Tests Run Example

### ISSUE THREAD

**Issue by trootcode** [Weingartner/SolidworksAddinFramework#10]
Can you show an example of how to run the unit tests.  Here is what I tried:
![image](https://cloud.githubusercontent.com/assets/19738245/15944086/b83037b6-2e40-11e6-9470-7db91073d55c.png)

**Comment by johannesegger** [comment]
I created a page in the documentation for [running automated tests](https://github.com/Weingartner/SolidworksAddinFramework/wiki/Running-automated-tests).

**Comment by trootcode** [comment]
Great!  The sample console call you provided worked for me!  I did notice, though, that is launched SW 2015 instead of 2016.  I have 3 copies of SolidWorks installed which makes things complicated sometimes.  I found one area of the code that references the SolidWorks exe to call but I changed that and compiled and it is still launching SW 2015.  Is there another place to look or somewhere else I could check?  Here is the one I changed:
![image](https://cloud.githubusercontent.com/assets/19738245/15954744/85f35c48-2e8f-11e6-9f27-6bf5aa289cfa.png)

**Comment by bradphelan** [comment]
If you run
![image](https://cloud.githubusercontent.com/assets/17650/15954781/5140d240-2edb-11e6-9b06-2f13419465ca.png)
does it launch the solidworks version you expect?

**Comment by trootcode** [comment]
yes, that launches the 2016 version of SolidWorks.

**Comment by trootcode** [comment]
how does xunit know where to find the xunit.solidworks.addin.dll?  Do I need to compile this in Release mode or something instead of debug mode?

**Comment by johannesegger** [comment]
It's a normal SW addin. SW finds it when you install it into the GAC by using the `regaddin.ps1` script. This triggers a call to `SwAddinBase.RegisterFunction` which creates a registry entry so that SW can find it.

**Comment by trootcode** [comment]
I rebuilt the solution and the tests are now launching SolidWorks 2016.  I bet it was launching SW 2015 because I hadn't rebuild the .spec projects.  I understand it a little better now.  I tried using the Visual Studio runner because that sounded easier than running these in the console but I wasn't able to get that to work.  It doesn't launch SolidWorks and gives me a deserialization error.  How do you run these tests?  Do you use the console?

**Comment by johannesegger** [comment]
We're using a [test runner plugin](https://resharper-plugins.jetbrains.com/packages/xunitcontrib/) for [ReSharper](https://www.jetbrains.com/resharper/), so we must admit that we never tried it with the VS runner. With the console runner however it worked for us. Can you check that?

**Comment by johannesegger** [comment]
I can verify that it didn't work with the VS runner. Although the runners all _should_ use the same code base, they seem to run tests a bit differently. However as of 24c23854ea0b5e35121240971cce3b31c0c73894 it also works with the VS runner.

**Comment by trootcode** [comment]
The console runner was working for all tests and now the VS runner also works.  Thanks for the fix!

**Comment by johannesegger** [comment]
You're welcome.

Side note: Please close an issue as soon as you consider it fixed. Thanks.
