### ISSUE TITLE
Persistent Reference Management

### ISSUE THREAD

**Issue by trootcode** [Weingartner/SolidworksAddinFramework#18]
When working with some SolidWorks API objects like `Body2`, `Feature`or `Face2`certain changes will cause the references to break.  For example, if you get a collection of `Body2` objects using `GetBodies2` of the `PartDoc` and then change the active configuration for that part you will likely lose those references even if you re-activate the original configuration.  You can get around this by getting the persistent reference to the object and then using that to get a fresh reference of that object before doing anything to it.  This works but quickly makes for a lot of code.  You have worked out some ways to handle this when working with selected objects using the `SelectionData` and `ObjectId` classes.  Have you thought about something similar to keep a persistent reference to objects that have not been selected?

**Comment by bradphelan** [comment]
In some place of our code we pass around `Func<Curve>` rather than `Curve` for this very problem. I'm not sure of a general solution. We regularly find things that break references. I still don't fully understand the object ownership and lifetimes of the solidworks objects.

**Comment by johannesegger** [comment]
Please take a look at #19.
