### ISSUE TITLE
Can't compile your code

### ISSUE THREAD

**Issue by borioan** [Weingartner/SolidworksAddinFramework#26]
Hello!
I'm interested in lunching SolidWorks from an exe file and access some add-ins **in-process**. For that I try to create a project from your source code but i got a lot of errors like:

_'..\..\Weingartner.WeinCad.Interfaces\Weingartner.WeinCad.Interfaces.csproj' does not exist.	SolidworksAddinFramework_			

or 

_This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is D:\GH\SolidworksAddinFramework\packages\Accord.3.0.2\build\Accord.targets_

If I try remove part of the errors directly editing SolidworksAddinFramework.csproj I got 15 other errors like 

_'..\..\packages\Weingartner.Json.Migration.Analyzer.1.0.5\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.dll' could not be found_	

What I'm missing? All I need is a simple solution to run **in-process** add-in for faster execution speed. As I understand XUnit.Solidworks.Addin could this but the project depends on the Addin framework project which has the compiler errors above. I'm using VisualStudio 2017. Any idea is welcome!

**Comment by brawner** [comment]
@borioan I'm having a similar issue. What did you do to get this to work?
