### ISSUE TITLE
I can't get the split part test project to work

### ISSUE THREAD

**Issue by trootcode** [Weingartner/SolidworksAddinFramework#7]
I tried running the sample add-in but am getting an error when I try to alpha split a part:
![image](https://cloud.githubusercontent.com/assets/19738245/15912480/646d79ac-2d89-11e6-8ee4-ea4c7350bab5.png)

An exception happens here:
![image](https://cloud.githubusercontent.com/assets/19738245/15909526/90733d06-2d7b-11e6-9aa1-687447185db5.png)

I dug into this a bit but couldn't make any sense out of what is supposed to happen.  The database Body SelectionData is empty when Regenerate is called but had one item selected when the Commit was called.

**Comment by johannesegger** [comment]
The library we are using here doesn't allow escaping from an `Optional` with `null` by default. If you want to do this, you have to call `MatchUnsafe` instead of `Match`. Fixed with eb6e462.

**Comment by bradphelan** [comment]
@trootcode For your interest we heavily use this library.

https://github.com/louthy/language-ext

It has some really nice features. Option<T> is the most common one you will find in our code. It makes it really clear that are either returning Some<T> or None<T> and you are forced to handle both cases to extract the value. Its a strategy to avoid random nullreferenceexceptions. See the [one billion dollar mistake ](https://www.linkedin.com/pulse/20141126171912-7082046-tony-hoare-invention-of-the-null-reference-a-billion-dollar-mistake).

Except with interop with legacy code we sometime need to return null. Hence the error in the demo above. I refactored the code from using our own Maybe<T> type to the LanguageExt.Optional<T> type and the semantics were a little different if you really forced the code to return **null**

Thanks for picking up the error. Thanks @eggapauli for fixing it.

**Comment by trootcode** [comment]
That fixed the error from being raised and created the feature but the split doesn't happen.

**Comment by bradphelan** [comment]
When you debug it are there multiple bodies returned from the regenerate method. Put a breakpoint there and check

![image](https://cloud.githubusercontent.com/assets/17650/15954367/7a07ab4a-2ed6-11e6-845a-41f75281debd.png)

splitBodies.

I haven't played with this demo for a while. Maybe something is broken with it.

**Comment by trootcode** [comment]
With the json fix I sent a pull request for the splitBodies count is 2.
Without the fix it never gets to that line.  MatchUnsafe is required
because it returns a null.

-Tim
